### ISSUE TITLE
Support for different number of objects in key and query views

### ISSUE THREAD

**Issue by ishitamed19** [sakshamjindal/non-metric_3d_representation#35]
If the key view and query view have a different number of objects - the present code will break - Find a possible way of fixing that and also to calculate the contrastive loss between them (how to determine if the object in both scenes are similar or not)

**Comment by ishitamed19** [comment]
one way is to just remove all those views which output <N boxes (similar too score matrix approach)

**Comment by sakshamjindal** [comment]
Closing for now ..
